<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>

    <!-- Microsoft Extensions -->

    <!-- Testing -->

    <!-- Logging -->

    <!-- Serialization -->

    <!-- Mapping -->

    <!-- Validation -->

  </ItemGroup>

</Project>